# Generated by Django 4.2.4 on 2023-08-07 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Appli", "0002_alter_sheet1_table"),
    ]

    operations = [
        migrations.AlterModelTable(name="sheet1", table="sheet1",),
    ]
