# Generated by Django 4.2.4 on 2023-08-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appli", "0003_alter_sheet1_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sheet2",
            fields=[
                ("serialno", models.IntegerField(primary_key=True, serialize=False)),
                ("word", models.CharField(blank=True, max_length=150, null=True)),
                ("origin", models.CharField(blank=True, max_length=25, null=True)),
                ("meaning", models.CharField(blank=True, max_length=2000, null=True)),
                ("sentence", models.CharField(blank=True, max_length=2000, null=True)),
                ("used", models.BooleanField(blank=True, null=True)),
            ],
            options={"db_table": "sheet2", "managed": False,},
        ),
        migrations.CreateModel(
            name="Sheet4",
            fields=[
                ("serialno", models.IntegerField(primary_key=True, serialize=False)),
                ("word", models.CharField(blank=True, max_length=150, null=True)),
                ("origin", models.CharField(blank=True, max_length=25, null=True)),
                ("meaning", models.CharField(blank=True, max_length=2000, null=True)),
                ("sentence", models.CharField(blank=True, max_length=2000, null=True)),
                ("used", models.BooleanField(blank=True, null=True)),
            ],
            options={"db_table": "sheet4", "managed": False,},
        ),
        migrations.CreateModel(
            name="Sheet5",
            fields=[
                ("serialno", models.IntegerField(primary_key=True, serialize=False)),
                ("word", models.CharField(blank=True, max_length=150, null=True)),
                ("origin", models.CharField(blank=True, max_length=25, null=True)),
                ("meaning", models.CharField(blank=True, max_length=2000, null=True)),
                ("sentence", models.CharField(blank=True, max_length=2000, null=True)),
                ("used", models.BooleanField(blank=True, null=True)),
            ],
            options={"db_table": "sheet5", "managed": False,},
        ),
    ]
