# Generated by Django 4.2.4 on 2023-08-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appli", "0004_sheet2_sheet4_sheet5"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sheet3",
            fields=[
                ("serialno", models.IntegerField(primary_key=True, serialize=False)),
                ("word", models.CharField(blank=True, max_length=150, null=True)),
                ("origin", models.CharField(blank=True, max_length=25, null=True)),
                ("meaning", models.CharField(blank=True, max_length=2000, null=True)),
                ("sentence", models.CharField(blank=True, max_length=2000, null=True)),
                ("used", models.BooleanField(blank=True, null=True)),
            ],
            options={"db_table": "sheet3", "managed": False,},
        ),
    ]
