# Generated by Django 4.2.4 on 2023-08-07 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Appli", "0005_sheet3"),
    ]

    operations = [
        migrations.DeleteModel(name="Sheet3",),
    ]
